openapi: 3.0.1
info:
  title: FirstToDoAPI
  description: API Definition of FirstToDoAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/work
paths:
  /todo:
    get:
      responses:
        default:
          description: Default response
